[api]
enabled = true
address = "127.0.0.1:8383"

[sources.docker]
type = "docker_logs"
docker_host = "/var/run/docker.sock"
include_containers = ["pix_erase.api"]

[sinks.console]
type = "console"
inputs = ["docker"]
encoding.codec = "json"

[sinks.loki_sync_id]
type = "loki"
inputs = ["docker"]
encoding.codec = "json"
labels.event = "log"
labels.container_name = "{{container_name}}"
endpoint = "http://pix_erase.loki:3100"
