global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api"
    scrape_interval: 30s
    static_configs:
      - targets: ["pix_erase.api:8080"]
    metrics_path: "/metrics"
    scrape_timeout: 10s

  - job_name: "worker"
    scrape_interval: 30s
    static_configs:
      - targets: [ "pix_erase.worker:8081" ]
    metrics_path: "/metrics"
    scrape_timeout: 10s