auth_enabled: false

target: all

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  http_server_read_timeout: 3m
  http_server_write_timeout: 3m
  grpc_server_max_recv_msg_size: 104857600 # 100 Mb
  grpc_server_max_send_msg_size: 104857600 # 100 Mb
  log_level: info

ingester_client:
  grpc_client_config:
    max_recv_msg_size: 104857600  # 100 Mb
    max_send_msg_size: 104857600  # 100 Mb

storage_config:
  tsdb_shipper:
    active_index_directory: /tmp/loki/tsdb-shipper-active
    cache_location: /tmp/loki/cache
    cache_ttl: 24h

compactor:
  working_directory: /tmp/loki/compactor
  compaction_interval: 5m
  retention_enabled: true
  delete_request_store: s3
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

ingester:
  chunk_encoding: snappy
  chunk_idle_period: 2h
  chunk_target_size: 1536000
  max_chunk_age: 2h
  wal:
    enabled: true
    dir: /tmp/loki/wal
    checkpoint_duration: 5m
    flush_on_shutdown: true

common:
  replication_factor: 1
  path_prefix: /tmp/loki
  storage:
    s3:
      endpoint: ${MINIO_HOST}:${MINIO_PORT}
      bucketnames: ${MINIO_LOKI_CHUNKS_BUCKET}
      access_key_id: ${MINIO_ROOT_USER}
      secret_access_key: ${MINIO_ROOT_PASSWORD}
      insecure: true
      s3forcepathstyle: true
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - chunks:
        period: 24h
        prefix: loki_chunks_
      from: 2023-01-01
      index:
        period: 24h
        prefix: loki_index_
      store: tsdb
      object_store: s3
      schema: v13

query_range:
  parallelise_shardable_queries: false
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

querier:
  max_concurrent: 2048

limits_config:
  allow_structured_metadata: true
  max_query_parallelism: 24
  split_queries_by_interval: 15m
  ingestion_rate_mb: 64
  ingestion_burst_size_mb: 128
  per_stream_rate_limit: "3MB"
  per_stream_rate_limit_burst: "10MB"
  retention_period: 24h
  reject_old_samples: true
  max_global_streams_per_user: 5000

frontend:
  max_outstanding_per_tenant: 4096
  compress_responses: true
  log_queries_longer_than: 5s

ruler:
  storage:
    type: s3
    s3:
      endpoint: ${MINIO_HOST}:${MINIO_PORT}
      bucketnames: ${MINIO_LOKI_RULES_BUCKET}
      insecure: true
      access_key_id: ${MINIO_ROOT_USER}
      secret_access_key: ${MINIO_ROOT_PASSWORD}
      s3forcepathstyle: true
